FileVersion = 1
Dependencies = {}

[Project]
Name = "corlib"
TargetType = "BeefLib"
DefaultNamespace = "System"

[[Project.DistinctOptions]]
Filter = "[System.DisableChecks]"
RuntimeChecks = false

[Configs.Debug2.Win64]

[[Configs.Debug2.Win64.DistinctOptions]]
Filter = "[System.Optimize]"
BfOptimizationLevel = "O2"
RuntimeChecks = false
EmitDynamicCastCheck = false
EmitObjectAccessCheck = false

[Configs.Debug.Win64]

[[Configs.Debug.Win64.DistinctOptions]]
Filter = "[System.Optimize]"
BfOptimizationLevel = "O2"
