FileVersion = 1
Dependencies = {corlib = "*", Beefy2D = "*"}

[Project]
Name = "BeefPerf"
TargetType = "BeefWindowsApplication"
StartupObject = "BeefPerf.Program"

[Platform.Windows]
IconFile = "res/BeefPerf.ico"
ManifestFile = "res/BeefPerf.manifest"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
TargetName = "$(ProjectName)_d"
OtherLinkFlags = "$(LinkFlags) BeefySysLib64_d.lib"
BeefLibType = "DynamicDebug"

[Configs.Debug.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Paranoid.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Paranoid.Win64]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win64]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
OtherLinkFlags = "$(LinkFlags) BeefySysLib64.lib"
BeefLibType = "Dynamic"
