FileVersion = 1
Dependencies = {Beefy2D = "*", corlib = "*"}

[Project]
Name = "IDE"
TargetType = "BeefWindowsApplication"
StartupObject = "IDE.Program"

[Platform.Windows]
IconFile = "$(WorkspaceDir)/Resources/Beef.ico"
ManifestFile = "$(WorkspaceDir)/Resources/IDE.manifest"
Description = "Beef IDE"
Comments = "a"
Company = "BeefyTechZ"
Product = "Beef IDE"
Copyright = "Copyright 2018 BeefyTech"
FileVersion = "0.42"
ProductVersion = "0.42"

[Configs.Debug.Win32]
TargetName = ""
OtherLinkFlags = ""
OptimizationLevel = "O0"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "BeefIDE_d"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib BeefySysLib64_d.lib"
CLibType = "Dynamic"
DebugCommandArguments = "-proddir=C:\\Beef\\BeefTools\\BeefInstall"
DebugWorkingDirectory = "c:\\Beef\\IDE\\Tests\\EmptyTest"
EnvironmentVars = ["_NO_DEBUG_HEAP=1"]

[Configs.Release.Win32]
TargetName = ""
OtherLinkFlags = ""
OptimizationLevel = "O0"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "BeefIDE"
OtherLinkFlags = "Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib Beef042RT64.lib IDEHelper64.lib BeefySysLib64.lib"
CLibType = "Dynamic"
DebugCommandArguments = "-proddir=\\Beef\\IDE\\Tests\\Rando -test=\\Beef\\IDE\\Tests\\scripts\\DebugAndExit.txt -testNoExit"
DebugWorkingDirectory = "$(ProjectDir)\\dist"
EnvironmentVars = ["_NO_DEBUG_HEAP=1"]

[Configs.Debug2.Win32]
TargetName = ""
OtherLinkFlags = ""
OptimizationLevel = "O0"

[Configs.Debug2.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "BeefIDE_d2"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib BeefySysLib64_d.lib wsock32.lib"
CLibType = "Dynamic"
BeefLibType = "DynamicDebug"
DebugCommandArguments = "-proddir=C:\\Beef\\IDE\\mintest -dbgCompileDump"
DebugWorkingDirectory = "$(ProjectDir)\\dist"
EnvironmentVars = ["_NO_DEBUG_HEAP=1"]

[Configs.Paranoid.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "BeefIDE_p"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib BeefySysLib64_d.lib wsock32.lib"

[Configs.Paranoid.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win64]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Debug3.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "BeefIDE_d3"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib BeefySysLib64_d.lib wsock32.lib"
BeefLibType = "DynamicDebug"
EnvironmentVars = ["_NO_DEBUG_HEAP=1"]
