FileVersion = 1

[Project]
Name = "DocPrep"
StartupObject = "DocPrep.Program"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/../../IDE/dist"
OtherLinkFlags = "$(LinkFlags) IDEHelper64_d.lib"
DebugCommandArguments = "c:\\beef\\BeefLibs\\corlib\\_test c:\\beef\\hugo\\temp"
