FileVersion = 1

[Project]
Name = "Beefy2D"
TargetType = "BeefLib"
DefaultNamespace = ""

[Configs.Debug.Win32]
OtherLinkFlags = ""
PreprocessorMacros = ["DEBUG", "BF32"]
OptimizationLevel = "O0"

[Configs.Debug.Win64]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Release.Win32]
OtherLinkFlags = ""
PreprocessorMacros = ["RELEASE", "BF32"]
OptimizationLevel = "O0"

[Configs.Paranoid.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Paranoid.Win64]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win64]
CLibType = "Static"
BeefLibType = "Static"
