FileVersion = 1

[Project]
Name = "BeefySysLib"
TargetType = "CustomBuild"

[Configs.Debug.Win32]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
TargetName = "BeefySysLib32_d.dll"
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
PostBuildCmds = ["\"$(WorkspaceDir)\\..\\bin\\msbuild.bat\" \"$(WorkspaceDir)\\..\\BeefySysLib\\BeefySysLib.vcxproj\" /p:Configuration=Debug /p:Platform=X86 /p:SolutionDir=$(Slash \"$(WorkspaceDir)\\\\..\\\\\") /v:m"]

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
TargetName = "BeefySysLib64_d.dll"
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
PostBuildCmds = ["\"$(WorkspaceDir)\\..\\bin\\msbuild.bat\" \"$(WorkspaceDir)\\..\\BeefySysLib\\BeefySysLib.vcxproj\" /p:Configuration=Debug /p:Platform=X64 /p:SolutionDir=$(Slash \"$(WorkspaceDir)\\\\..\\\\\") /v:m"]

[Configs.Release.Win32]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
TargetName = "BeefySysLib32.dll"
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
PostBuildCmds = ["\"$(WorkspaceDir)\\..\\bin\\msbuild.bat\" \"$(WorkspaceDir)\\..\\BeefySysLib\\BeefySysLib.vcxproj\" /p:Configuration=Release /p:Platform=X86 /p:SolutionDir=$(Slash \"$(WorkspaceDir)\\\\..\\\\\") /v:m"]

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
TargetName = "BeefySysLib64.dll"
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
PostBuildCmds = ["\"$(WorkspaceDir)\\..\\bin\\msbuild.bat\" \"$(WorkspaceDir)\\..\\BeefySysLib\\BeefySysLib.vcxproj\" /p:Configuration=Release /p:Platform=X64 /p:SolutionDir=$(Slash \"$(WorkspaceDir)\\\\..\\\\\") /v:m"]

[Configs.Paranoid.Win32]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"

[Configs.Paranoid.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"

[Configs.Test.Win32]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"

[Configs.Test.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"

[ProjectFolder]

[[ProjectFolder.Items]]
Type = "Folder"
Name = "fbx"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "fbx/FBXReader.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "fbx/FBXReader.h"

[[ProjectFolder.Items]]
Type = "Folder"
Name = "gfx"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/DrawLayer.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/DrawLayer.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/FTFont.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/FTFont.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/ModelDef.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/ModelDef.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/ModelInstance.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/ModelInstance.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/RenderCmd.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/RenderCmd.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/RenderDevice.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/RenderDevice.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/RenderTarget.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/RenderTarget.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/Shader.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/Shader.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/Texture.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "gfx/Texture.h"

[[ProjectFolder.Items]]
Type = "Folder"
Name = "img"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/BFIData.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/BFIData.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/ImageAdjustments.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/ImageAdjustments.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/ImageData.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/ImageData.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/ImageUtils.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/ImageUtils.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/ImgEffects.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/ImgEffects.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/JPEGData.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/JPEGData.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/PNGData.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/PNGData.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/PSDReader.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/PSDReader.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/PVRData.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/PVRData.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/TGAData.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "img/TGAData.h"

[[ProjectFolder.Items]]
Type = "Folder"
Name = "platform"

[[ProjectFolder.Items.Items]]
Type = "Folder"
Name = "win"

[[ProjectFolder.Items.Items.Items]]
Type = "Source"
Path = "platform/win/BFPlatform.h"

[[ProjectFolder.Items.Items.Items]]
Type = "Source"
Path = "platform/win/DXRenderDevice.cpp"

[[ProjectFolder.Items.Items.Items]]
Type = "Source"
Path = "platform/win/DXRenderDevice.h"

[[ProjectFolder.Items.Items.Items]]
Type = "Source"
Path = "platform/win/Platform.cpp"

[[ProjectFolder.Items.Items.Items]]
Type = "Source"
Path = "platform/win/PlatformApp.h"

[[ProjectFolder.Items.Items.Items]]
Type = "Source"
Path = "platform/win/WinBFApp.cpp"

[[ProjectFolder.Items.Items.Items]]
Type = "Source"
Path = "platform/win/WinBFApp.h"

[[ProjectFolder.Items]]
Type = "Folder"
Name = "sound"

[[ProjectFolder.Items]]
Type = "Folder"
Name = "util"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/AllocDebug.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/AllocDebug.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "util/BeefPerf.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "util/BeefPerf.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/BSpline.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/BSpline.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/BumpAllocator.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/CatmullRom.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/CatmullRom.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/CritSect.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/CubicFuncSpline.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/CubicFuncSpline.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/CubicSpline.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/CubicSpline.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/DLIList.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Hash.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Hash.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Json.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Json.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Matrix4.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Matrix4.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/PerfTimer.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/PerfTimer.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Point.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Point.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/PolySpline.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/PolySpline.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Quaternion.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Quaternion.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Rect.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/SLIList.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "util/TLSingleton.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/UTF8.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/UTF8.h"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Vector.cpp"

[[ProjectFolder.Items.Items]]
Type = "Source"
Path = "Util/Vector.h"

[[ProjectFolder.Items]]
Type = "Source"
Path = "BeefySysLib.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "BFApp.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "BFApp.h"

[[ProjectFolder.Items]]
Type = "Source"
Path = "BFWindow.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "BFWindow.h"

[[ProjectFolder.Items]]
Type = "Source"
Path = "Common.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "Common.h"

[[ProjectFolder.Items]]
Type = "Source"
Path = "DataStream.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "DataStream.h"

[[ProjectFolder.Items]]
Type = "Source"
Path = "FileHandleStream.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "FileHandleStream.h"

[[ProjectFolder.Items]]
Type = "Source"
Path = "FileStream.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "FileStream.h"

[[ProjectFolder.Items]]
Type = "Source"
Path = "MemStream.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "MemStream.h"

[[ProjectFolder.Items]]
Type = "Source"
Path = "PerfTests.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "ResLib.cpp"

[[ProjectFolder.Items]]
Type = "Source"
Path = "Startup.cpp"
