FileVersion = 1
Dependencies = {minlib = "*"}

[Project]
Name = "mintest"
StartupObject = "Hey.Dude.Bro.TestClass"
DefaultNamespace = "Mintest"

[Platform.Windows]
Description = "Mintest"

[Configs.Debug.Win64]
CLibType = "Static"
BeefLibType = "DynamicDebug"
StackSize = 4194304
DebugCommandArguments = "abc"
DebugWorkingDirectory = ".\\"

[Configs.Debug.Win32]
CLibType = "DynamicDebug"
BeefLibType = "DynamicDebug"

[Configs.Debug.WinFart]
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[Configs.Debug.iOS]
BuildKind = "StaticLib"

[Configs.Debug.aarch64-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"

[Configs.Debug.wasm32]
PostBuildCmds = ["copy $(BuildDir)\\*.js $(ProjectDir)", "copy $(BuildDir)\\*.wasm $(ProjectDir)", "copy $(BuildDir)\\*.html $(ProjectDir)"]

[Configs.Release.Win64]
OtherLinkFlags = "$(LinkFlags) C:\\Beef\\BeefTools\\TestDLL\\x64\\Debug\\TestDLL.lib"
DebugCommandArguments = "hey=\"yo man\" zag= zoogles boof   stoopers   \"abc efg\""

[Configs.Release.WinFart]
OtherLinkFlags = ""

[Configs.Release.iOS]
BuildKind = "StaticLib"

[Configs.Release.aarch64-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"

[Configs.Paranoid.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Paranoid.Win64]
CLibType = "Static"
BeefLibType = "Static"
DebugCommandArguments = "paranoid"

[Configs.Paranoid.WinFart]
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[Configs.Paranoid.iOS]
BuildKind = "StaticLib"

[Configs.Paranoid.aarch64-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"

[Configs.Test.Win32]
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.Win64]
CLibType = "Static"
BeefLibType = "DynamicDebug"

[Configs.Test.WinFart]
BuildKind = "Normal"
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[Configs.Test.iOS]
BuildKind = "StaticLib"

[Configs.Test.aarch64-none-linux-android21]
BuildKind = "StaticLib"
RelocType = "PIC"

[Configs.NewDebug.Win64]
CLibType = "Static"
BeefLibType = "Static"
DebugCommandArguments = "abc"
DebugWorkingDirectory = ".\\"

[Configs.NewDebug.Win32]
CLibType = "DynamicDebug"
BeefLibType = "Static"

[Configs.NewDebug.WinFart]
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[Configs.NewDebug.iOS]
BeefLibType = "Static"

[Configs.NewDebug.aarch64-none-linux-android21]
BeefLibType = "Static"
RelocType = "PIC"
