FileVersion = 1
Dependencies = {}

[Project]
Name = "minlib"
TargetType = "BeefLib"
DefaultNamespace = ""

[Configs.Debug.Win32]
OtherLinkFlags = ""
OptimizationLevel = "O0"

[[Configs.Debug.Win32.DistinctOptions]]
Filter = "[System.Optimize]"
BfOptimizationLevel = "O2"
RuntimeChecks = false
EmitDynamicCastCheck = false
EmitObjectAccessCheck = false

[Configs.Debug.Win64]
CLibType = "Static"

[[Configs.Debug.Win64.DistinctOptions]]
Filter = "[System.Optimize]"
BfOptimizationLevel = "O2"
RuntimeChecks = false
EmitDynamicCastCheck = false
EmitObjectAccessCheck = false

[Configs.Debug.WinFart]
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[Configs.Release.Win32]
OtherLinkFlags = ""
OptimizationLevel = "O2"

[Configs.Release.Win64]
OtherLinkFlags = ""

[Configs.Release.WinFart]
OtherLinkFlags = ""

[Configs.Test.WinFart]
BuildKind = "Normal"
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"

[Configs.Paranoid.Win32]
CLibType = "Static"

[Configs.Paranoid.Win64]
CLibType = "Static"

[Configs.Paranoid.WinFart]
OtherLinkFlags = ""
CLibType = "Static"
BeefLibType = "Static"
